# Generated by Django 3.1.6 on 2021-02-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Nationality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
