# Generated by Django 3.1.6 on 2021-02-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210221_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Language',
            field=models.ManyToManyField(help_text='Select a language for this book', to='catalog.Language'),
        ),
    ]
